services:
  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    command: -c shared_buffers=8GB -c wal_level=minimal -c max_wal_senders=0 -c max_wal_size=2GB

volumes:
  data:
